// <auto-generated />
using System;
using FarmHelm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmHelm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FarmHelmDbContext))]
    partial class FarmHelmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("batch_code_seq");

            modelBuilder.HasSequence("crop_code_seq");

            modelBuilder.HasSequence("farm_code_seq");

            modelBuilder.HasSequence("farm_location_code_seq");

            modelBuilder.HasSequence("variety_code_seq");

            modelBuilder.Entity("FarmHelm.Domain.Crops.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("batch_code");

                    b.Property<Guid>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IndividualTrackingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("individual_tracking_enabled");

                    b.Property<int>("InitialPlantCount")
                        .HasColumnType("integer")
                        .HasColumnName("initial_plant_count");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PlantingDate")
                        .HasColumnType("date")
                        .HasColumnName("planting_date");

                    b.Property<DateOnly?>("RemovedDate")
                        .HasColumnType("date")
                        .HasColumnName("removed_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("VarietyId")
                        .HasColumnType("uuid")
                        .HasColumnName("variety_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("FarmId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PlantingDate");

                    b.HasIndex("Status");

                    b.HasIndex("VarietyId");

                    b.ToTable("batch", null, t =>
                        {
                            t.HasCheckConstraint("ck_batch_initial_plant_count_positive", "initial_plant_count > 0");
                        });
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.BatchStageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("StageId");

                    b.ToTable("batch_stage_history", (string)null);
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Crop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CropCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("crop_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id");

                    b.HasIndex("CropCode")
                        .IsUnique();

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("crop", (string)null);
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.CropStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("CropId", "Name")
                        .IsUnique();

                    b.ToTable("crop_stage", null, t =>
                        {
                            t.HasCheckConstraint("ck_crop_stage_display_order_non_negative", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.MortalityReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("mortality_reason", null, t =>
                        {
                            t.HasCheckConstraint("ck_mortality_reason_display_order_non_negative", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.MortalityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateOnly>("MortalityDate")
                        .HasColumnType("date")
                        .HasColumnName("mortality_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("reason_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MortalityDate");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.HasIndex("ReasonId");

                    b.HasIndex("PlantId", "BatchId");

                    b.ToTable("mortality_record", null, t =>
                        {
                            t.HasCheckConstraint("ck_mortality_record_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PlantCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("plant_code");

                    b.Property<int>("PlantNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plant_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("PlantCode")
                        .IsUnique();

                    b.HasIndex("BatchId", "PlantNumber")
                        .IsUnique();

                    b.ToTable("plant", null, t =>
                        {
                            t.HasCheckConstraint("ck_plant_plant_number_positive", "plant_number > 0");
                        });
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Variety", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uuid")
                        .HasColumnName("crop_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("VarietyCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("variety_code");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("VarietyCode")
                        .IsUnique();

                    b.HasIndex("CropId", "Name")
                        .IsUnique();

                    b.ToTable("variety", (string)null);
                });

            modelBuilder.Entity("FarmHelm.Domain.Farms.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("FarmCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("farm_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id");

                    b.HasIndex("FarmCode")
                        .IsUnique();

                    b.ToTable("farm", (string)null);
                });

            modelBuilder.Entity("FarmHelm.Domain.Farms.FarmLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("farm_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("location_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("farm_location", (string)null);
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Batch", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.CropStage", null)
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmHelm.Domain.Farms.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmHelm.Domain.Farms.FarmLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FarmHelm.Domain.Crops.Variety", null)
                        .WithMany()
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.BatchStageHistory", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.Batch", null)
                        .WithMany("StageHistory")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmHelm.Domain.Crops.CropStage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Crop", b =>
                {
                    b.HasOne("FarmHelm.Domain.Farms.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.CropStage", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.Crop", null)
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.MortalityReason", b =>
                {
                    b.HasOne("FarmHelm.Domain.Farms.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.MortalityRecord", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.Batch", null)
                        .WithMany("MortalityRecords")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmHelm.Domain.Crops.MortalityReason", null)
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmHelm.Domain.Crops.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId", "BatchId")
                        .HasPrincipalKey("Id", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Plant", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.Batch", null)
                        .WithMany("Plants")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Variety", b =>
                {
                    b.HasOne("FarmHelm.Domain.Crops.Crop", null)
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Farms.FarmLocation", b =>
                {
                    b.HasOne("FarmHelm.Domain.Farms.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmHelm.Domain.Crops.Batch", b =>
                {
                    b.Navigation("MortalityRecords");

                    b.Navigation("Plants");

                    b.Navigation("StageHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
